---
- name: 02-updateServer
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no

  vars:
    become: yes
    become_method: sudo 

  tasks:

  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    ansible.builtin.apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
    become: true

  - name: Upgrade all apt packages
    ansible.builtin.apt:
      upgrade: yes
      force_apt_get: yes
    become: true

  - name: Upgrade all apt packages
    ansible.builtin.apt:
      apt: upgrade=dist force_apt_get=yes
    become: true

  - name: Check if a reboot is needed
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no
    become: true