---
- name: 07-initializeMasterNode
  hosts: localhost
  become_method: sudo
  gather_facts: no

  vars:
    #become: yes
    #become_method: sudo 

  tasks:

  #Check br_netfilter status
  - name: make sure that the br_netfilter module is loaded
    shell: lsmod | grep br_netfilter
    register: netfilterOutput
    become: yes

  - debug:
      msg: "{{ item }}"
    with_items: "{{ netfilterOutput.stdout_lines }}"

  #Enable kubelet service.
  - name: Enable service kubelet
    ansible.builtin.systemd:
      name: kubelet
      enabled: yes
    become: yes

  #Pull container images:
  - name: make sure that the br_netfilter module is loaded
    command: sudo kubeadm config images pull
    become: yes

  #Add hostname&ip address for DNS resolver in Master node I.E: ansible-playbook -e "serverIp=192.168.1.101 serverFqdn=sgre-k8s-master"
  - name: make sure that the br_netfilter module is loaded
    shell: sudo echo "{{serverIp}} {{serverFqdn}}" >> /etc/hosts
    become: yes

  - name: Add Cri-o repo
    shell: | 
      sudo kubeadm init \
      --pod-network-cidr=192.168.0.0/16 \
      --upload-certs \
      --control-plane-endpoint={{serverFqdn}}
    register: kubeadmInit
    #become: yes

  - debug:
      msg: "{{ kubeadmInit.stdout_lines }}"
    # with_items: "{{ kubeadmInit.stdout_lines }}"

  - name: configure kube
    shell: mkdir -p $HOME/.kube

  - name: configure kube
    shell: sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
  
  - name: configure kube
    shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Check cluster-info
    shell: kubectl cluster-info
    register: clusterInfo

  - debug:
      msg: "{{ clusterInfo.stdout_lines }}"
